In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\AI_Course\ModularProgramProjects\finalProject\data\scraped_raw_data\car_data.csv")

In [3]:
df.sample(4)

,Name,Range_km,Efficiency,Weight,Acceleration(0-100),Firth_stop_range,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price
245,BMW iX xDrive45,470 km,202 Wh/km,2525,5.1,490,94.8,115,2500,500,182,"€83,500"
760,Porsche Taycan Turbo,415 km,202 Wh/km,2380,3.2,518,83.7,200,0,450,367,"€156,348"
412,Mercedes-Benz EQE 300,525 km,170 Wh/km,2375,6.9,570,89.0,120,750,430,128,"€67,187"
438,Skoda Enyaq 85x,455 km,169 Wh/km,2186,6.7,501,77.0,120,1800,585,113,"€51,500"

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 1200 non-null   str
 1   Range_km             1200 non-null   str
 2   Efficiency           1200 non-null   str
 3   Weight               1200 non-null   int64
 4   Acceleration(0-100)  1200 non-null   float64
 5   Firth_stop_range     1200 non-null   int64
 6   Battery_kWh          1200 non-null   float64
 7   Fast_charger(kW)     1200 non-null   int64
 8   Towing_kg            1200 non-null   int64
 9   Cargo_volume         1200 non-null   int64
 10  Price/Range(km)      1200 non-null   int64
 11  Price                1110 non-null   str
dtypes: float64(2), int64(6), str(4)
memory usage: 112.6 KB

In [13]:
cols = ['Range_km','Efficiency','Price']

df[cols] = df[cols].replace(r"[^ 0-9 , .]", '', regex=True)

df[['Range_km','Efficiency']] = df[['Range_km','Efficiency']].astype(int)
df['Price'] = df['Price'].str.replace(',','.').astype(float)

df = df.rename(columns={'Weight':'Weight_kg', 'Firth_stop_range':'Firth_stop_range_km','Price':'Price_Euro'})

In [18]:
df.head()

,Name,Range_km,Efficiency,Weight_kg,Acceleration(0-100),Firth_stop_range_km,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price_Euro
0,BMW iX3 50 xDrive,610,178,2360,4.9,742,108.7,230,2000,578,114,70.900
1,Tesla Model Y Long Range RWD,490,157,1953,7.2,574,77.0,130,1600,952,100,47.970
2,Mercedes-Benz CLA 250+,585,145,2055,6.7,746,85.0,208,1500,506,92,55.728
3,MG MG4 Electric 64 kWh,360,171,1726,7.9,401,61.7,107,500,363,103,39.990
4,Tesla Model 3 RWD,445,135,1847,6.2,523,60.0,110,1000,682,89,37.970

In [23]:
df1 = df[df['Price_Euro'].isnull()]

df1['Price_Euro'] = (df1['Range_km'] * df1['Price/Range(km)']) / 1000

123433.212

In [24]:
df1

,Name,Range_km,Efficiency,Weight_kg,Acceleration(0-100),Firth_stop_range_km,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price_Euro
16,BYD ATTO 3 Evo RWD Design,415,180,1880,5.5,472,74.8,130,1500,591,111,46.065
35,Jaecoo 5 EV,325,181,1765,7.7,341,58.9,80,1250,480,96,31.200
68,Toyota bZ4X Touring AWD 74.7 kWh,385,184,2075,4.4,419,71.0,110,1500,600,138,53.130
95,Omoda E5,330,178,1785,7.6,350,58.9,80,0,380,103,33.990
96,Mazda 6e 78 kWh,470,164,2090,7.9,545,77.0,135,1500,528,95,44.650
...,...,...,...,...,...,...,...,...,...,...,...,...
1138,Skywell BE11 Standard Range,325,209,1955,9.6,296,68.0,50,0,467,131,42.575
1149,Toyota Proace Shuttle M 75 kWh,265,260,2131,13.1,252,69.0,77,1000,550,227,60.155
1169,Toyota Proace Shuttle L 75 kWh,265,260,2161,13.1,252,69.0,77,1000,980,263,69.695
1189,Toyota Proace Shuttle M 50 kWh,185,250,1969,12.1,196,46.3,74,1000,550,318,58.830
1199,Toyota Proace Shuttle L 50 kWh,180,257,1989,12.1,189,46.3,74,1000,980,381,68.580

In [25]:
df.head()

,Name,Range_km,Efficiency,Weight_kg,Acceleration(0-100),Firth_stop_range_km,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price_Euro
0,BMW iX3 50 xDrive,610,178,2360,4.9,742,108.7,230,2000,578,114,70.900
1,Tesla Model Y Long Range RWD,490,157,1953,7.2,574,77.0,130,1600,952,100,47.970
2,Mercedes-Benz CLA 250+,585,145,2055,6.7,746,85.0,208,1500,506,92,55.728
3,MG MG4 Electric 64 kWh,360,171,1726,7.9,401,61.7,107,500,363,103,39.990
4,Tesla Model 3 RWD,445,135,1847,6.2,523,60.0,110,1000,682,89,37.970

In [27]:
df = df.dropna()

In [31]:
new_df = pd.concat([df, df1])

In [32]:
new_df.info()

<class 'pandas.DataFrame'>
Index: 1200 entries, 0 to 1199
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 1200 non-null   str
 1   Range_km             1200 non-null   int64
 2   Efficiency           1200 non-null   int64
 3   Weight_kg            1200 non-null   int64
 4   Acceleration(0-100)  1200 non-null   float64
 5   Firth_stop_range_km  1200 non-null   int64
 6   Battery_kWh          1200 non-null   float64
 7   Fast_charger(kW)     1200 non-null   int64
 8   Towing_kg            1200 non-null   int64
 9   Cargo_volume         1200 non-null   int64
 10  Price/Range(km)      1200 non-null   int64
 11  Price_Euro           1200 non-null   float64
dtypes: float64(3), int64(8), str(1)
memory usage: 121.9 KB

In [34]:
new_df.head()

,Name,Range_km,Efficiency,Weight_kg,Acceleration(0-100),Firth_stop_range_km,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price_Euro
0,BMW iX3 50 xDrive,610,178,2360,4.9,742,108.7,230,2000,578,114,70.900
1,Tesla Model Y Long Range RWD,490,157,1953,7.2,574,77.0,130,1600,952,100,47.970
2,Mercedes-Benz CLA 250+,585,145,2055,6.7,746,85.0,208,1500,506,92,55.728
3,MG MG4 Electric 64 kWh,360,171,1726,7.9,401,61.7,107,500,363,103,39.990
4,Tesla Model 3 RWD,445,135,1847,6.2,523,60.0,110,1000,682,89,37.970

In [35]:
import os
path = r"C:\Users\bunyo\OneDrive\Desktop\AI_Course\ModularProgramProjects\finalProject\data\raw_data"

full_data_path = os.path.join(path,"cleaned_raw_data.csv")
new_df.to_csv(full_data_path, index = False)

In [36]:
new_df.corrwith(df['Price_Euro']).sort_values(ascending=False)

ValueError: could not convert string to float: 'BMW iX3 50 xDrive'