In [3]:
import pandas as pd

In [17]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\AI_Course\ModularProgramProjects\finalProject\data\scraped_raw_data\car_data.csv")

In [12]:
df.sample(4)

,Name,Range_km,Efficiency,Weight,Acceleration(0-100),Firth_stop_range,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price
832,Polestar 2 Long Range Performance,385 km,195 Wh/km,2188,4.4,402,75.0,97,1500,440,162,"€61,495"
105,Kia e-Niro 64 kWh,375 km,171 Wh/km,1812,7.8,349,64.0,61,300,451,108,"€42,790"
607,XPENG P7+ RWD Standard Range,375 km,160 Wh/km,2074,6.9,491,60.0,220,1500,573,124,"€46,600"
596,Mitsubishi i-MiEV,85 km,171 Wh/km,1160,15.9,98,14.5,30,0,166,310,"€23,790"

In [ ]:
cols = ['Range_km','Efficiency','Price']

df[cols] = df[cols].replace(r"[^ 0-9 , .]", '', regex=True)

df[['Range_km','Efficiency']] = df[['Range_km','Efficiency']].astype(int)
df['Price'] = df['Price'].str.replace(',','.').astype(float)

df = df.rename(columns={'Weight':'Weight_kg', 'Firth_stop_range':'Firth_stop_range_km','Price':'Price_Euro'})

In [22]:
df.head()

,Name,Range_km,Efficiency,Weight,Acceleration(0-100),Firth_stop_range,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price
0,BMW iX3 50 xDrive,610,178,2360,4.9,742,108.7,230,2000,578,114,70.900
1,Tesla Model Y Long Range RWD,490,157,1953,7.2,574,77.0,130,1600,952,100,47.970
2,Mercedes-Benz CLA 250+,585,145,2055,6.7,746,85.0,208,1500,506,92,55.728
3,MG MG4 Electric 64 kWh,360,171,1726,7.9,401,61.7,107,500,363,103,39.990
4,Tesla Model 3 RWD,445,135,1847,6.2,523,60.0,110,1000,682,89,37.970

In [24]:
df = df.rename(columns={'Weight':'Weight_kg', 'Firth_stop_range':'Firth_stop_range_km','Price':'Price_Euro'})

,Name,Range_km,Efficiency,Weight_kg,Acceleration(0-100),Firth_stop_range_km,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price_Euro
0,BMW iX3 50 xDrive,610,178,2360,4.9,742,108.7,230,2000,578,114,70.900
1,Tesla Model Y Long Range RWD,490,157,1953,7.2,574,77.0,130,1600,952,100,47.970
2,Mercedes-Benz CLA 250+,585,145,2055,6.7,746,85.0,208,1500,506,92,55.728
3,MG MG4 Electric 64 kWh,360,171,1726,7.9,401,61.7,107,500,363,103,39.990
4,Tesla Model 3 RWD,445,135,1847,6.2,523,60.0,110,1000,682,89,37.970

In [8]:
df.corrwith(df['Price']).sort_values(ascending=False)

ValueError: could not convert string to float: '€70,900'